### ISSUE TITLE
Smart amount of snow [feature request]

### ISSUE THREAD

**Issue by m0oncatcher** [ToBinio/better-snow-coverage#2]
Right now even one random snow layer can spread a whole bunch of snow around itself, which can be unrealistic looking and also undesirable. Following some logic from your other mod, the "dense flowers", can the radius of spread start at 0 for 1 snow layer, but the more of it is in the same area, the further it can spread?

**Comment by ToBinio** [comment]
I now made it so it always prefers the closes one

![2024-08-18_08 05 57](https://github.com/user-attachments/assets/45f43d70-0889-4abf-9732-76f36954cc5c)
![2024-08-18_08 05 40](https://github.com/user-attachments/assets/0c0f1d78-bcae-43b7-a56c-0ae0feb202ae)

not exactly what you suggested but it does the same job
thoughts?

**Comment by m0oncatcher** [comment]
I'm not really getting how it works, do you mind explaining? Especially the screenshots - i can't understand.

**Comment by ToBinio** [comment]
I check all 4 directions for what block it is
snow, air, unknown (nonfull block e.g grass)

if all blocks are unknown I do the same but this time one block further out

If at least one snow or one air block exists, I check which is more common (preferring snow if both are equal) and if snow wins I render a snow layer.

---

in the first screenshot, you can see one grass block not rendering snow since it's connected to 1 air block and 3 unknowns
so no snow is renderd

in the second you have the same case but inverted. you can also see a grass block next to 1 snow, 2 air, and 1 unknown so no snow is rendered

--- 

I hope this makes it clearer

**Comment by ToBinio** [comment]
i now released a new version with this implementation - [v 0.1.1](https://modrinth.com/mod/better-snow-coverage/version/0.1.0+mc1.21.0)
